#pragma once
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <vector>
#include <iostream>
#include "Sky.hpp"
#include "Model.hpp"
#include "MountainFG.hpp"
#include "MountainBG.hpp"
#include "Cloud.hpp"
#include "Ball.hpp"
#include "Square.hpp"
#include "Eyes.hpp"
#include "Star.hpp"
#include "Mouth.hpp"
#define GLT_IMPLEMENTATION
#include "gltext.h"